// The Layer 1 endpoint registry (spec §6.3, §6.4). One entry per operation:
// it drives the OpenAPI paths, the api's route table check, the contract tests
// (permission, envelope, idempotency, If-Match) and the generated cross-tenant
// tests (spec §6.8). Paths are relative to /api/v1 and use OpenAPI `{param}`.

import { PhotoAnnotation, PhotoAnnotationCreate, PhotoAnnotationUpdate } from "./annotations.ts";
import { AuditEvent, AuditEventQuery } from "./audit.ts";
import {
  AccessTokenResult,
  AuthTokens,
  InvitationAcceptRequest,
  Jwks,
  LoginRequest,
  MfaEnrollment,
  MfaEnrollmentConfirmRequest,
  MfaEnrollmentRequest,
  MfaVerifyRequest,
  PasswordChangeRequest,
  PasswordForgotRequest,
  PasswordResetRequest,
  RefreshRequest,
  SessionInfo,
  SessionListItem,
  SwitchOrganizationRequest,
} from "./auth.ts";
import {
  BeforeAfterSet,
  BeforeAfterSetCreate,
  BeforeAfterSetListQuery,
  BeforeAfterSetUpdate,
} from "./before-after.ts";
import {
  EffectiveOfflineCachePolicy,
  FeatureFlag,
  FeatureFlagPut,
  FeatureFlagQuery,
  PracticeSetting,
  PracticeSettingPut,
  RetentionPolicy,
  RetentionPolicyCreate,
  RetentionPolicyListQuery,
} from "./configuration.ts";
import {
  Consultation,
  ConsultationCancel,
  ConsultationComplete,
  ConsultationConcernsPut,
  ConsultationCreate,
  ConsultationListQuery,
  ConsultationNote,
  ConsultationNoteCreate,
  ConsultationNoteListQuery,
  ConsultationNoteUpdate,
  ConsultationUpdate,
  MedicalHistoryCreate,
  MedicalHistoryEntry,
  MedicalHistoryListQuery,
  MedicalHistoryUpdate,
  PatientConcern,
  PatientConcernCreate,
  PatientConcernListQuery,
  PatientConcernUpdate,
} from "./consultations.ts";
import {
  Document,
  DocumentAccessUrl,
  DocumentAccessUrlRequest,
  DocumentListQuery,
  DocumentUploadComplete,
  DocumentUploadIntent,
  DocumentUploadRequest,
  TimelineItem,
  TimelineQuery,
} from "./documents.ts";
import { BeforeAfterExportCreate, ExportAccessUrl, MediaExport, PhotoExportCreate } from "./exports.ts";
import {
  AdminBootstrapResult,
  FirstAdmin,
  Location,
  LocationCreate,
  LocationListQuery,
  LocationUpdate,
  Organization,
  OrganizationCreate,
  OrganizationCreated,
  OrganizationUpdate,
  Practice,
  PracticeCreate,
  PracticeUpdate,
} from "./organizations.ts";
import { PageQuery } from "./pagination.ts";
import {
  DuplicateCheckRequest,
  DuplicateCheckResult,
  Patient,
  PatientContact,
  PatientContactCreate,
  PatientContactUpdate,
  PatientCreate,
  PatientListQuery,
  PatientProfile,
  PatientSearchRequest,
  PatientSummary,
  PatientUpdate,
} from "./patients.ts";
import {
  AccessUrl,
  AccessUrlRequest,
  BatchAccessUrlRequest,
  BatchAccessUrls,
  MediaRelease,
  MediaReleaseCreate,
  MediaReleaseListQuery,
  MediaReleaseRevoke,
  OfflineAuditBatch,
  OfflineAuditResult,
  Photo,
  PhotographyProtocol,
  PhotographyProtocolCreate,
  PhotographyProtocolListQuery,
  PhotographyProtocolUpdate,
  PhotoListQuery,
  PhotoPermission,
  PhotoPermissionChange,
  PhotoPermissionHistoryQuery,
  PhotoPermissionSummary,
  PhotoSession,
  PhotoSessionComplete,
  PhotoSessionCreate,
  PhotoSessionListQuery,
  PhotoTagsPut,
  PhotoUploadIntent,
  PhotoUploadRequest,
} from "./photography.ts";
import { Uuid } from "./primitives.ts";
import {
  HealthStatus,
  OrganizationSetting,
  OrganizationSettingKeySchema,
  OrganizationSettingPut,
} from "./settings.ts";
import {
  MfaResetRequest,
  MfaResetResult,
  PermissionInfo,
  ProviderProfile,
  ProviderProfilePut,
  Role,
  RoleAssignment,
  RoleAssignmentCreate,
  SessionsRevokeResult,
  StaffProfile,
  StaffProfilePut,
  StaffUser,
  UserCreate,
  UserListQuery,
  UserUpdate,
} from "./users.ts";
import { z } from "./zod.ts";

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

/** Where a permission is evaluated (spec §4.6). */
export type PermissionScope = "organization" | "platform";

export type EndpointAuth =
  /** No credentials (login, reset, health, JWKS). */
  | { readonly kind: "public" }
  /** A token in the body proves the caller: an MFA challenge, refresh, invitation or reset token. */
  | {
      readonly kind: "token";
      readonly token: "challenge" | "refresh" | "invitation" | "reset" | "challenge-or-session";
    }
  /** Any valid session; the operation only touches the caller's own account. */
  | { readonly kind: "session" }
  /**
   * A permission, evaluated per request from the caller's grants (never from the
   * token). `orPermissions` lists alternatives that also admit the caller; the
   * handler then applies the rule that needs one of them specifically.
   * `alsoRequires` lists permissions the caller must hold as well.
   */
  | {
      readonly kind: "permission";
      readonly permission: string;
      readonly orPermissions?: readonly string[];
      readonly alsoRequires?: readonly string[];
      readonly scopes: readonly PermissionScope[];
    };

export type ResponseShape = "resource" | "collection" | "none" | "bare";

export interface EndpointDefinition {
  readonly operationId: string;
  readonly method: HttpMethod;
  readonly path: string;
  readonly tag:
    | "Auth"
    | "Organizations"
    | "Users"
    | "Roles"
    | "Patients"
    | "Photography"
    | "Consultations"
    | "Documents"
    | "Audit"
    | "Settings"
    | "Health";
  readonly summary: string;
  readonly auth: EndpointAuth;
  /** Needs a recent MFA (ADR-0021 step-up); else 403 REAUTHENTICATION_REQUIRED. */
  readonly stepUp?: boolean;
  readonly params?: z.ZodObject;
  readonly query?: z.ZodObject;
  readonly body?: z.ZodType;
  readonly response: {
    readonly status: 200 | 201 | 202 | 204;
    readonly shape: ResponseShape;
    readonly schema?: z.ZodType;
    /** Returns `ETag: "v{version}"`. */
    readonly etag?: boolean;
  };
  /** `Idempotency-Key` required (spec §6.1.8). */
  readonly idempotency?: "required";
  /** `If-Match` required (spec §6.1.7); "when-exists" for create-or-replace PUTs. */
  readonly ifMatch?: "required" | "when-exists";
  /** Code returned for an absent, other-tenant or out-of-scope path resource (spec §6.1.10). */
  readonly notFound?: `${string}_NOT_FOUND`;
  /** Audit actions the operation can write. */
  readonly audit?: readonly string[];
  /** Touches patient data: denials are audited as ACCESS_DENIED (ADR-0018 K-10). */
  readonly patientData?: boolean;
  /** Extra error statuses beyond the ones implied by auth, params and headers. */
  readonly errors?: readonly number[];
}

const IdParam = z.strictObject({ id: Uuid });
const PatientParam = z.strictObject({ patientId: Uuid });
const ContactParams = z.strictObject({ patientId: Uuid, contactId: Uuid });
const AssignmentParams = z.strictObject({ id: Uuid, assignmentId: Uuid });
const SettingParam = z.strictObject({ key: z.string().min(1).max(100) });
const PracticeSettingParams = z.strictObject({ practiceId: Uuid, key: z.string().min(1).max(100) });
const SessionParams = z.strictObject({ patientId: Uuid, sessionId: Uuid });
const PhotoParams = z.strictObject({ patientId: Uuid, photoId: Uuid });
const ReleaseParams = z.strictObject({ patientId: Uuid, releaseId: Uuid });
const ConsultationParams = z.strictObject({ patientId: Uuid, consultationId: Uuid });
const NoteParams = z.strictObject({ patientId: Uuid, consultationId: Uuid, noteId: Uuid });
const ConcernParams = z.strictObject({ patientId: Uuid, concernId: Uuid });
const HistoryParams = z.strictObject({ patientId: Uuid, entryId: Uuid });
const SetParams = z.strictObject({ patientId: Uuid, setId: Uuid });
const AnnotationParams = z.strictObject({ patientId: Uuid, photoId: Uuid, annotationId: Uuid });
const ExportParams = z.strictObject({ patientId: Uuid, exportId: Uuid });
const DocumentParams = z.strictObject({ patientId: Uuid, documentId: Uuid });

const perm = (permission: string, ...scopes: PermissionScope[]): EndpointAuth => ({
  kind: "permission",
  permission,
  scopes: scopes.length > 0 ? scopes : ["organization"],
});
/**
 * Exports and releases also need photo.view: MARKETING holds photo.export for
 * released assets only and sees no patient (spec §4.5 note ¹; ADR-0027, F-71).
 */
const EXPORTER: EndpointAuth = {
  kind: "permission",
  permission: "photo.export",
  alsoRequires: ["photo.view"],
  scopes: ["organization"],
};
const RELEASER: EndpointAuth = {
  kind: "permission",
  permission: "photo.export",
  orPermissions: ["consultation.complete"],
  alsoRequires: ["photo.view"],
  scopes: ["organization"],
};
const permAny = (permission: string, ...orPermissions: string[]): EndpointAuth => ({
  kind: "permission",
  permission,
  orPermissions,
  scopes: ["organization"],
});
const SESSION: EndpointAuth = { kind: "session" };
const PUBLIC: EndpointAuth = { kind: "public" };

export const ENDPOINTS = [
  // ---- Auth & session -------------------------------------------------------
  {
    operationId: "login",
    method: "POST",
    path: "/auth/login",
    tag: "Auth",
    summary: "Sign in with email and password. 401 MFA_REQUIRED carries a challenge in error.details.",
    auth: PUBLIC,
    body: LoginRequest,
    response: { status: 200, shape: "resource", schema: AuthTokens },
    audit: ["LOGIN_SUCCESS", "LOGIN_FAILURE"],
    errors: [401, 429],
  },
  {
    operationId: "verifyMfa",
    method: "POST",
    path: "/auth/mfa/verify",
    tag: "Auth",
    summary: "Complete a sign-in MFA challenge with a TOTP code or a passkey assertion.",
    auth: { kind: "token", token: "challenge" },
    body: MfaVerifyRequest,
    response: { status: 200, shape: "resource", schema: AuthTokens },
    audit: ["LOGIN_SUCCESS", "LOGIN_FAILURE"],
    errors: [401, 429],
  },
  {
    operationId: "refreshToken",
    method: "POST",
    path: "/auth/token/refresh",
    tag: "Auth",
    summary:
      "Rotate the refresh token. The admin web sends no body: the cookie carries it and Origin is checked.",
    auth: { kind: "token", token: "refresh" },
    body: RefreshRequest,
    response: { status: 200, shape: "resource", schema: AuthTokens },
    audit: ["SECURITY_SESSION_REVOKED"],
    errors: [401, 403],
  },
  {
    operationId: "logout",
    method: "POST",
    path: "/auth/logout",
    tag: "Auth",
    summary: "Revoke the current session.",
    auth: SESSION,
    response: { status: 204, shape: "none" },
    audit: ["LOGOUT"],
  },
  {
    operationId: "getSession",
    method: "GET",
    path: "/auth/session",
    tag: "Auth",
    summary:
      "The signed-in user, active organization, memberships and effective permissions (UI hints only).",
    auth: SESSION,
    response: { status: 200, shape: "resource", schema: SessionInfo },
  },
  {
    operationId: "switchOrganization",
    method: "PUT",
    path: "/auth/session/organization",
    tag: "Auth",
    summary: "Bind the session to another active membership and issue new tokens.",
    auth: SESSION,
    body: SwitchOrganizationRequest,
    response: { status: 200, shape: "resource", schema: AccessTokenResult },
    audit: ["ORGANIZATION_SWITCHED"],
    errors: [403, 404],
    notFound: "ORGANIZATION_NOT_FOUND",
  },
  {
    operationId: "listOwnSessions",
    method: "GET",
    path: "/auth/sessions",
    tag: "Auth",
    summary: "The caller's active sessions and devices.",
    auth: SESSION,
    query: PageQuery,
    response: { status: 200, shape: "collection", schema: SessionListItem },
  },
  {
    operationId: "revokeOwnSession",
    method: "DELETE",
    path: "/auth/sessions/{id}",
    tag: "Auth",
    summary: "Revoke one of the caller's sessions.",
    auth: SESSION,
    params: IdParam,
    response: { status: 204, shape: "none" },
    notFound: "SESSION_NOT_FOUND",
    audit: ["SECURITY_SESSION_REVOKED"],
  },
  {
    operationId: "forgotPassword",
    method: "POST",
    path: "/auth/password/forgot",
    tag: "Auth",
    summary: "Email a reset link if the account exists. The response is identical either way.",
    auth: PUBLIC,
    body: PasswordForgotRequest,
    response: { status: 202, shape: "none" },
    errors: [429],
  },
  {
    operationId: "resetPassword",
    method: "POST",
    path: "/auth/password/reset",
    tag: "Auth",
    summary: "Set a new password with the emailed token. Revokes every session of the user.",
    auth: { kind: "token", token: "reset" },
    body: PasswordResetRequest,
    response: { status: 204, shape: "none" },
    audit: ["SECURITY_CREDENTIAL_CHANGED", "SECURITY_SESSION_REVOKED"],
    errors: [401],
  },
  {
    operationId: "changePassword",
    method: "POST",
    path: "/auth/password/change",
    tag: "Auth",
    summary: "Change the password (current password and a recent MFA). Ends the user's other sessions.",
    auth: SESSION,
    stepUp: true,
    body: PasswordChangeRequest,
    response: { status: 204, shape: "none" },
    audit: ["SECURITY_CREDENTIAL_CHANGED", "SECURITY_SESSION_REVOKED"],
    errors: [403],
  },
  {
    operationId: "acceptInvitation",
    method: "POST",
    path: "/auth/invitations/accept",
    tag: "Auth",
    summary:
      "Accept a staff invitation: set the password (or prove the current one) and activate the membership.",
    auth: { kind: "token", token: "invitation" },
    body: InvitationAcceptRequest,
    response: { status: 204, shape: "none" },
    audit: ["SECURITY_CREDENTIAL_CHANGED", "USER_UPDATED"],
    errors: [401],
  },
  {
    operationId: "createMfaEnrollment",
    method: "POST",
    path: "/auth/mfa/enrollments",
    tag: "Auth",
    summary:
      "Start enrolling a TOTP or passkey factor. During sign-in, TOTP may be enrolled with the challenge.",
    auth: { kind: "token", token: "challenge-or-session" },
    stepUp: true,
    body: MfaEnrollmentRequest,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: MfaEnrollment },
    errors: [403],
  },
  {
    operationId: "confirmMfaEnrollment",
    method: "POST",
    path: "/auth/mfa/enrollments/{id}/confirm",
    tag: "Auth",
    summary: "Confirm a pending factor with a TOTP code or the passkey registration.",
    auth: { kind: "token", token: "challenge-or-session" },
    stepUp: true,
    params: IdParam,
    body: MfaEnrollmentConfirmRequest,
    response: { status: 204, shape: "none" },
    notFound: "FACTOR_NOT_FOUND",
    audit: ["SECURITY_CREDENTIAL_CHANGED"],
    errors: [403],
  },
  {
    operationId: "deleteMfaEnrollment",
    method: "DELETE",
    path: "/auth/mfa/enrollments/{id}",
    tag: "Auth",
    summary: "Remove one of the caller's second factors. The last factor of a user who must use MFA stays.",
    auth: SESSION,
    stepUp: true,
    params: IdParam,
    response: { status: 204, shape: "none" },
    notFound: "FACTOR_NOT_FOUND",
    audit: ["SECURITY_CREDENTIAL_CHANGED"],
    errors: [403, 409],
  },
  {
    operationId: "getJwks",
    method: "GET",
    path: "/.well-known/jwks.json",
    tag: "Auth",
    summary: "Public keys that verify access tokens.",
    auth: PUBLIC,
    response: { status: 200, shape: "bare", schema: Jwks },
  },

  // ---- Organizations, practices, locations ---------------------------------
  {
    operationId: "listOrganizations",
    method: "GET",
    path: "/organizations",
    tag: "Organizations",
    summary: "List organizations (platform scope).",
    auth: perm("organization.read", "platform"),
    query: PageQuery,
    response: { status: 200, shape: "collection", schema: Organization },
  },
  {
    operationId: "createOrganization",
    method: "POST",
    path: "/organizations",
    tag: "Organizations",
    summary: "Create an organization and invite its first ORGANIZATION_ADMIN (platform scope).",
    auth: perm("organization.manage", "platform"),
    body: OrganizationCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: OrganizationCreated, etag: true },
    audit: ["CONFIGURATION_CHANGED", "USER_CREATED", "ROLE_ASSIGNED"],
    errors: [409],
  },
  {
    operationId: "getOrganization",
    method: "GET",
    path: "/organizations/{id}",
    tag: "Organizations",
    summary: "View the caller's organization, or any organization at platform scope.",
    auth: perm("organization.read", "organization", "platform"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: Organization, etag: true },
    notFound: "ORGANIZATION_NOT_FOUND",
  },
  {
    operationId: "updateOrganization",
    method: "PATCH",
    path: "/organizations/{id}",
    tag: "Organizations",
    summary: "Rename the caller's organization; change any organization's status at platform scope.",
    auth: perm("organization.manage", "organization", "platform"),
    params: IdParam,
    body: OrganizationUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Organization, etag: true },
    notFound: "ORGANIZATION_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
  },
  {
    operationId: "bootstrapOrganizationAdmin",
    method: "POST",
    path: "/organizations/{id}/admin-bootstrap",
    tag: "Organizations",
    summary:
      "Invite the first ORGANIZATION_ADMIN of an organization that has no active one (platform scope).",
    auth: perm("organization.manage", "platform"),
    params: IdParam,
    body: FirstAdmin,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: AdminBootstrapResult },
    notFound: "ORGANIZATION_NOT_FOUND",
    audit: ["USER_CREATED", "ROLE_ASSIGNED"],
    errors: [403, 409],
  },
  {
    operationId: "listPractices",
    method: "GET",
    path: "/practices",
    tag: "Organizations",
    summary: "Practices of the organization.",
    auth: perm("practice.read"),
    query: PageQuery,
    response: { status: 200, shape: "collection", schema: Practice },
  },
  {
    operationId: "createPractice",
    method: "POST",
    path: "/practices",
    tag: "Organizations",
    summary: "Create a practice (organization-scope grant).",
    auth: perm("practice.manage"),
    body: PracticeCreate,
    response: { status: 201, shape: "resource", schema: Practice, etag: true },
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },
  {
    operationId: "getPractice",
    method: "GET",
    path: "/practices/{id}",
    tag: "Organizations",
    summary: "View a practice.",
    auth: perm("practice.read"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: Practice, etag: true },
    notFound: "PRACTICE_NOT_FOUND",
  },
  {
    operationId: "updatePractice",
    method: "PATCH",
    path: "/practices/{id}",
    tag: "Organizations",
    summary: "Update a practice within the caller's scope.",
    auth: perm("practice.manage"),
    params: IdParam,
    body: PracticeUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Practice, etag: true },
    notFound: "PRACTICE_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },
  {
    operationId: "listLocations",
    method: "GET",
    path: "/locations",
    tag: "Organizations",
    summary: "Locations of the organization's practices.",
    auth: perm("practice.read"),
    query: LocationListQuery,
    response: { status: 200, shape: "collection", schema: Location },
  },
  {
    operationId: "createLocation",
    method: "POST",
    path: "/locations",
    tag: "Organizations",
    summary: "Create a location in a practice within the caller's scope.",
    auth: perm("practice.manage"),
    body: LocationCreate,
    response: { status: 201, shape: "resource", schema: Location, etag: true },
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409, 404],
  },
  {
    operationId: "getLocation",
    method: "GET",
    path: "/locations/{id}",
    tag: "Organizations",
    summary: "View a location.",
    auth: perm("practice.read"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: Location, etag: true },
    notFound: "LOCATION_NOT_FOUND",
  },
  {
    operationId: "updateLocation",
    method: "PATCH",
    path: "/locations/{id}",
    tag: "Organizations",
    summary: "Update a location within the caller's scope.",
    auth: perm("practice.manage"),
    params: IdParam,
    body: LocationUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Location, etag: true },
    notFound: "LOCATION_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },

  // ---- Users, roles, permissions --------------------------------------------
  {
    operationId: "listUsers",
    method: "GET",
    path: "/users",
    tag: "Users",
    summary: "Members of the organization (filter by status, practice, role).",
    auth: perm("user.read"),
    query: UserListQuery,
    response: { status: 200, shape: "collection", schema: StaffUser },
  },
  {
    operationId: "createUser",
    method: "POST",
    path: "/users",
    tag: "Users",
    summary: "Invite a person to the organization, optionally with role assignments.",
    auth: perm("user.create"),
    body: UserCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: StaffUser, etag: true },
    audit: ["USER_CREATED", "ROLE_ASSIGNED"],
    errors: [409],
  },
  {
    operationId: "getUser",
    method: "GET",
    path: "/users/{id}",
    tag: "Users",
    summary: "View a member.",
    auth: perm("user.read"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: StaffUser, etag: true },
    notFound: "USER_NOT_FOUND",
  },
  {
    operationId: "updateUser",
    method: "PATCH",
    path: "/users/{id}",
    tag: "Users",
    summary: "Update a member's name or phone.",
    auth: perm("user.update"),
    params: IdParam,
    body: UserUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: StaffUser, etag: true },
    notFound: "USER_NOT_FOUND",
    audit: ["USER_UPDATED"],
  },
  {
    operationId: "disableUser",
    method: "POST",
    path: "/users/{id}/disable",
    tag: "Users",
    summary: "Disable the membership and revoke the user's sessions in this organization.",
    auth: perm("user.disable"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: StaffUser, etag: true },
    notFound: "USER_NOT_FOUND",
    audit: ["USER_DISABLED", "SECURITY_SESSION_REVOKED"],
    errors: [409],
  },
  {
    operationId: "createRoleAssignment",
    method: "POST",
    path: "/users/{id}/role-assignments",
    tag: "Users",
    summary: "Assign a role at a scope (never to oneself, never beyond one's own scope).",
    auth: perm("role.assign"),
    params: IdParam,
    body: RoleAssignmentCreate,
    response: { status: 201, shape: "resource", schema: RoleAssignment },
    notFound: "USER_NOT_FOUND",
    audit: ["ROLE_ASSIGNED"],
    errors: [409],
  },
  {
    operationId: "revokeRoleAssignment",
    method: "DELETE",
    path: "/users/{id}/role-assignments/{assignmentId}",
    tag: "Users",
    summary: "Revoke a role assignment.",
    auth: perm("role.assign"),
    params: AssignmentParams,
    response: { status: 204, shape: "none" },
    notFound: "ROLE_ASSIGNMENT_NOT_FOUND",
    audit: ["ROLE_REVOKED"],
  },
  {
    operationId: "getProviderProfile",
    method: "GET",
    path: "/users/{id}/provider-profile",
    tag: "Users",
    summary: "The member's provider profile.",
    auth: perm("user.read"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: ProviderProfile, etag: true },
    notFound: "PROVIDER_PROFILE_NOT_FOUND",
  },
  {
    operationId: "putProviderProfile",
    method: "PUT",
    path: "/users/{id}/provider-profile",
    tag: "Users",
    summary: "Create or replace the provider profile (If-Match once it exists).",
    auth: perm("user.update"),
    params: IdParam,
    body: ProviderProfilePut,
    ifMatch: "when-exists",
    response: { status: 200, shape: "resource", schema: ProviderProfile, etag: true },
    notFound: "USER_NOT_FOUND",
    audit: ["USER_UPDATED"],
  },
  {
    operationId: "getStaffProfile",
    method: "GET",
    path: "/users/{id}/staff-profile",
    tag: "Users",
    summary: "The member's staff profile.",
    auth: perm("user.read"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: StaffProfile, etag: true },
    notFound: "STAFF_PROFILE_NOT_FOUND",
  },
  {
    operationId: "putStaffProfile",
    method: "PUT",
    path: "/users/{id}/staff-profile",
    tag: "Users",
    summary: "Create or replace the staff profile (If-Match once it exists).",
    auth: perm("user.update"),
    params: IdParam,
    body: StaffProfilePut,
    ifMatch: "when-exists",
    response: { status: 200, shape: "resource", schema: StaffProfile, etag: true },
    notFound: "USER_NOT_FOUND",
    audit: ["USER_UPDATED"],
  },
  {
    operationId: "revokeUserSessions",
    method: "POST",
    path: "/users/{id}/sessions/revoke",
    tag: "Users",
    summary: "Revoke the user's sessions bound to this organization; at platform scope, all of them.",
    auth: perm("security.manage", "organization", "platform"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: SessionsRevokeResult },
    notFound: "USER_NOT_FOUND",
    audit: ["SECURITY_SESSION_REVOKED"],
  },
  {
    operationId: "resetUserMfa",
    method: "POST",
    path: "/users/{id}/mfa-reset",
    tag: "Users",
    summary: "Remove every second factor of a user who lost them, and revoke all their sessions.",
    auth: perm("security.manage", "organization", "platform"),
    stepUp: true,
    params: IdParam,
    body: MfaResetRequest,
    response: { status: 200, shape: "resource", schema: MfaResetResult },
    notFound: "USER_NOT_FOUND",
    audit: ["SECURITY_CREDENTIAL_CHANGED", "SECURITY_SESSION_REVOKED"],
  },
  {
    operationId: "listRoles",
    method: "GET",
    path: "/roles",
    tag: "Roles",
    summary: "Roles and their permissions.",
    auth: perm("role.read", "organization", "platform"),
    query: PageQuery,
    response: { status: 200, shape: "collection", schema: Role },
  },
  {
    operationId: "getRole",
    method: "GET",
    path: "/roles/{id}",
    tag: "Roles",
    summary: "One role and its permissions.",
    auth: perm("role.read", "organization", "platform"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: Role },
    notFound: "ROLE_NOT_FOUND",
  },
  {
    operationId: "listPermissions",
    method: "GET",
    path: "/permissions",
    tag: "Roles",
    summary: "The permission catalog.",
    auth: perm("role.read", "organization", "platform"),
    query: PageQuery,
    response: { status: 200, shape: "collection", schema: PermissionInfo },
  },

  // ---- Patients --------------------------------------------------------------
  {
    operationId: "searchPatients",
    method: "POST",
    path: "/patients/search",
    tag: "Patients",
    summary:
      "Search by a name prefix or an exact date of birth, MRN, email or phone. Terms travel in the body.",
    auth: perm("patient.read"),
    body: PatientSearchRequest,
    response: { status: 200, shape: "collection", schema: PatientSummary },
    patientData: true,
    errors: [429],
  },
  {
    operationId: "listPatients",
    method: "GET",
    path: "/patients",
    tag: "Patients",
    summary: "Recently updated patients, filtered by status or primary practice. No PHI in the query.",
    auth: perm("patient.read"),
    query: PatientListQuery,
    response: { status: 200, shape: "collection", schema: PatientSummary },
    patientData: true,
  },
  {
    operationId: "checkPatientDuplicates",
    method: "POST",
    path: "/patients/duplicate-check",
    tag: "Patients",
    summary: "Probable duplicates of a patient about to be created.",
    auth: perm("patient.create"),
    body: DuplicateCheckRequest,
    response: { status: 200, shape: "resource", schema: DuplicateCheckResult },
    patientData: true,
  },
  {
    operationId: "createPatient",
    method: "POST",
    path: "/patients",
    tag: "Patients",
    summary: "Create a patient. Probable duplicates need confirmNoDuplicate.",
    auth: perm("patient.create"),
    body: PatientCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: Patient, etag: true },
    audit: ["PATIENT_CREATED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "getPatient",
    method: "GET",
    path: "/patients/{patientId}",
    tag: "Patients",
    summary: "The patient profile: demographics, and which profile tabs the caller may read.",
    auth: perm("patient.read"),
    params: PatientParam,
    response: { status: 200, shape: "resource", schema: PatientProfile, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PATIENT_VIEWED"],
    patientData: true,
  },
  {
    operationId: "updatePatient",
    method: "PATCH",
    path: "/patients/{patientId}",
    tag: "Patients",
    summary: "Update demographics or set status ACTIVE, INACTIVE or DECEASED.",
    auth: perm("patient.update"),
    params: PatientParam,
    body: PatientUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Patient, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "archivePatient",
    method: "POST",
    path: "/patients/{patientId}/archive",
    tag: "Patients",
    summary: "Archive the patient. Records are kept.",
    auth: perm("patient.archive"),
    params: PatientParam,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Patient, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PATIENT_ARCHIVED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "listPatientContacts",
    method: "GET",
    path: "/patients/{patientId}/contacts",
    tag: "Patients",
    summary: "The patient's contacts.",
    auth: perm("patient.read"),
    params: PatientParam,
    query: PageQuery,
    response: { status: 200, shape: "collection", schema: PatientContact },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createPatientContact",
    method: "POST",
    path: "/patients/{patientId}/contacts",
    tag: "Patients",
    summary: "Add a contact.",
    auth: perm("patient.update"),
    params: PatientParam,
    body: PatientContactCreate,
    response: { status: 201, shape: "resource", schema: PatientContact, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "updatePatientContact",
    method: "PATCH",
    path: "/patients/{patientId}/contacts/{contactId}",
    tag: "Patients",
    summary: "Update a contact.",
    auth: perm("patient.update"),
    params: ContactParams,
    body: PatientContactUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: PatientContact, etag: true },
    notFound: "PATIENT_CONTACT_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "deletePatientContact",
    method: "DELETE",
    path: "/patients/{patientId}/contacts/{contactId}",
    tag: "Patients",
    summary: "Remove a contact.",
    auth: perm("patient.update"),
    params: ContactParams,
    response: { status: 204, shape: "none" },
    notFound: "PATIENT_CONTACT_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
  },

  // ---- Photography (spec §6.3 "Photography"; ADR-0023) ---------------------------
  {
    operationId: "listPhotographyProtocols",
    method: "GET",
    path: "/photography-protocols",
    tag: "Photography",
    summary: "The organization's photography protocols with their views.",
    auth: permAny("photo.view", "photo.capture", "practice.manage"),
    query: PhotographyProtocolListQuery,
    response: { status: 200, shape: "collection", schema: PhotographyProtocol },
  },
  {
    operationId: "createPhotographyProtocol",
    method: "POST",
    path: "/photography-protocols",
    tag: "Photography",
    summary: "Create a custom protocol as a DRAFT, optionally superseding another.",
    auth: perm("practice.manage"),
    body: PhotographyProtocolCreate,
    response: { status: 201, shape: "resource", schema: PhotographyProtocol, etag: true },
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },
  {
    operationId: "getPhotographyProtocol",
    method: "GET",
    path: "/photography-protocols/{id}",
    tag: "Photography",
    summary: "One protocol and its views.",
    auth: permAny("photo.view", "photo.capture", "practice.manage"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: PhotographyProtocol, etag: true },
    notFound: "PHOTOGRAPHY_PROTOCOL_NOT_FOUND",
  },
  {
    operationId: "updatePhotographyProtocol",
    method: "PATCH",
    path: "/photography-protocols/{id}",
    tag: "Photography",
    summary: "Edit a DRAFT protocol; views are replaced as a set. Active protocols are frozen.",
    auth: perm("practice.manage"),
    params: IdParam,
    body: PhotographyProtocolUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: PhotographyProtocol, etag: true },
    notFound: "PHOTOGRAPHY_PROTOCOL_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },
  {
    operationId: "activatePhotographyProtocol",
    method: "POST",
    path: "/photography-protocols/{id}/activate",
    tag: "Photography",
    summary: "Activate a DRAFT. A successor retires the protocol it supersedes in the same step.",
    auth: perm("practice.manage"),
    params: IdParam,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: PhotographyProtocol, etag: true },
    notFound: "PHOTOGRAPHY_PROTOCOL_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },
  {
    operationId: "retirePhotographyProtocol",
    method: "POST",
    path: "/photography-protocols/{id}/retire",
    tag: "Photography",
    summary: "Retire an ACTIVE protocol, or discard a DRAFT. Sessions already started continue.",
    auth: perm("practice.manage"),
    params: IdParam,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: PhotographyProtocol, etag: true },
    notFound: "PHOTOGRAPHY_PROTOCOL_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },
  {
    operationId: "listPhotoSessions",
    method: "GET",
    path: "/patients/{patientId}/photo-sessions",
    tag: "Photography",
    summary: "The patient's photo sessions, newest first.",
    auth: perm("photo.view"),
    params: PatientParam,
    query: PhotoSessionListQuery,
    response: { status: 200, shape: "collection", schema: PhotoSession },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createPhotoSession",
    method: "POST",
    path: "/patients/{patientId}/photo-sessions",
    tag: "Photography",
    summary: "Start a session under an ACTIVE protocol. A client UUIDv7 is accepted for offline capture.",
    auth: perm("photo.capture"),
    params: PatientParam,
    body: PhotoSessionCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: PhotoSession },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "getPhotoSession",
    method: "GET",
    path: "/patients/{patientId}/photo-sessions/{sessionId}",
    tag: "Photography",
    summary: "One session, with each view's capture state and the required views still missing.",
    auth: perm("photo.view"),
    params: SessionParams,
    response: { status: 200, shape: "resource", schema: PhotoSession },
    notFound: "PHOTO_SESSION_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "completePhotoSession",
    method: "POST",
    path: "/patients/{patientId}/photo-sessions/{sessionId}/complete",
    tag: "Photography",
    summary: "Complete a session. Missing required views need acknowledgeMissingRequiredViews.",
    auth: perm("photo.capture"),
    params: SessionParams,
    body: PhotoSessionComplete,
    response: { status: 200, shape: "resource", schema: PhotoSession },
    notFound: "PHOTO_SESSION_NOT_FOUND",
    patientData: true,
    errors: [409, 422],
  },
  {
    operationId: "listPhotos",
    method: "GET",
    path: "/patients/{patientId}/photos",
    tag: "Photography",
    summary: "The patient's photos, newest capture first. Archived photos only on request.",
    auth: perm("photo.view"),
    params: PatientParam,
    query: PhotoListQuery,
    response: { status: 200, shape: "collection", schema: Photo },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createPhotoUpload",
    method: "POST",
    path: "/patients/{patientId}/photos/uploads",
    tag: "Photography",
    summary: "Upload intent: registers the photo and returns a presigned PUT for its original.",
    auth: perm("photo.capture"),
    params: PatientParam,
    body: PhotoUploadRequest,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: PhotoUploadIntent },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
    errors: [409, 413, 415, 503],
  },
  {
    operationId: "completePhotoUpload",
    method: "POST",
    path: "/patients/{patientId}/photos/{photoId}/complete-upload",
    tag: "Photography",
    summary: "Verify the uploaded original (size, checksum, type) and hand it to the malware scan.",
    auth: perm("photo.capture"),
    params: PhotoParams,
    idempotency: "required",
    response: { status: 200, shape: "resource", schema: Photo },
    notFound: "PHOTO_NOT_FOUND",
    audit: ["PHOTO_CAPTURED"],
    patientData: true,
    errors: [409, 413, 415, 422, 503],
  },
  {
    operationId: "getPhoto",
    method: "GET",
    path: "/patients/{patientId}/photos/{photoId}",
    tag: "Photography",
    summary: "Photo metadata, scan state and derivative availability. No image bytes.",
    auth: perm("photo.view"),
    params: PhotoParams,
    response: { status: 200, shape: "resource", schema: Photo },
    notFound: "PHOTO_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createPhotoAccessUrl",
    method: "POST",
    path: "/patients/{patientId}/photos/{photoId}/access-urls",
    tag: "Photography",
    summary: "A signed GET for one variant, valid 120 seconds. ORIGINAL needs photo.export.",
    auth: perm("photo.view"),
    params: PhotoParams,
    body: AccessUrlRequest,
    response: { status: 201, shape: "resource", schema: AccessUrl },
    notFound: "PHOTO_NOT_FOUND",
    audit: ["PHOTO_VIEWED"],
    patientData: true,
    errors: [409, 503],
  },
  {
    operationId: "createPhotoAccessUrls",
    method: "POST",
    path: "/patients/{patientId}/photos/access-urls",
    tag: "Photography",
    summary: "Signed thumbnail or preview URLs for up to 60 photos (galleries). One PHOTO_VIEWED per photo.",
    auth: perm("photo.view"),
    params: PatientParam,
    body: BatchAccessUrlRequest,
    response: { status: 201, shape: "resource", schema: BatchAccessUrls },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PHOTO_VIEWED"],
    patientData: true,
    errors: [503],
  },
  {
    operationId: "replacePhotoTags",
    method: "PUT",
    path: "/patients/{patientId}/photos/{photoId}/tags",
    tag: "Photography",
    summary: "Replace the photo's tags.",
    auth: perm("photo.annotate"),
    params: PhotoParams,
    body: PhotoTagsPut,
    response: { status: 200, shape: "resource", schema: Photo },
    notFound: "PHOTO_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "archivePhoto",
    method: "POST",
    path: "/patients/{patientId}/photos/{photoId}/archive",
    tag: "Photography",
    summary: "Archive an accepted photo. The original is kept; archived photos are never reused.",
    auth: perm("photo.capture"),
    params: PhotoParams,
    response: { status: 200, shape: "resource", schema: Photo },
    notFound: "PHOTO_NOT_FOUND",
    audit: ["PHOTO_ARCHIVED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "getPhotoPermissions",
    method: "GET",
    path: "/patients/{patientId}/photo-permissions",
    tag: "Photography",
    summary: "The current media permission per category, with per-photo and per-session exceptions.",
    auth: perm("photo.permission.read"),
    params: PatientParam,
    response: { status: 200, shape: "resource", schema: PhotoPermissionSummary },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "listPhotoPermissionHistory",
    method: "GET",
    path: "/patients/{patientId}/photo-permissions/history",
    tag: "Photography",
    summary: "Every version of the patient's media permissions, newest first.",
    auth: perm("photo.permission.read"),
    params: PatientParam,
    query: PhotoPermissionHistoryQuery,
    response: { status: 200, shape: "collection", schema: PhotoPermission },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "recordPhotoPermission",
    method: "POST",
    path: "/patients/{patientId}/photo-permissions",
    tag: "Photography",
    summary: "Record a media permission transition. Online only; ending a grant revokes the releases on it.",
    auth: perm("photo.permission.manage"),
    params: PatientParam,
    body: PhotoPermissionChange,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: PhotoPermission },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PHOTO_PERMISSION_CHANGED", "MEDIA_RELEASE_REVOKED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "listMediaReleases",
    method: "GET",
    path: "/patients/{patientId}/media-releases",
    tag: "Photography",
    summary: "Releases of the patient's media, newest first.",
    auth: perm("photo.view"),
    params: PatientParam,
    query: MediaReleaseListQuery,
    response: { status: 200, shape: "collection", schema: MediaRelease },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createMediaRelease",
    method: "POST",
    path: "/patients/{patientId}/media-releases",
    tag: "Photography",
    summary: "Release a photo for one purpose, pinning the permission version it relies on.",
    auth: RELEASER,
    params: PatientParam,
    body: MediaReleaseCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: MediaRelease },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["MEDIA_RELEASED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "revokeMediaRelease",
    method: "POST",
    path: "/patients/{patientId}/media-releases/{releaseId}/revoke",
    tag: "Photography",
    summary: "Revoke a release. It stays on record with its pins.",
    auth: RELEASER,
    params: ReleaseParams,
    body: MediaReleaseRevoke,
    response: { status: 200, shape: "resource", schema: MediaRelease },
    notFound: "MEDIA_RELEASE_NOT_FOUND",
    audit: ["MEDIA_RELEASE_REVOKED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "recordOfflineAuditEvents",
    method: "POST",
    path: "/audit/offline-events",
    tag: "Audit",
    summary: "Replay views recorded offline, with their original times (spec §8 rule 8). Own views only.",
    auth: SESSION,
    body: OfflineAuditBatch,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: OfflineAuditResult },
    audit: ["PATIENT_VIEWED", "PHOTO_VIEWED"],
    patientData: true,
  },

  // ---- Annotations (spec §6.3 "Photography"; ADR-0026 K3-10) ---------------------
  {
    operationId: "listPhotoAnnotations",
    method: "GET",
    path: "/patients/{patientId}/photos/{photoId}/annotations",
    tag: "Photography",
    summary: "The photo's annotation layers, oldest first. Deleted layers are not listed.",
    auth: perm("photo.view"),
    params: PhotoParams,
    response: { status: 200, shape: "collection", schema: PhotoAnnotation },
    notFound: "PHOTO_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createPhotoAnnotation",
    method: "POST",
    path: "/patients/{patientId}/photos/{photoId}/annotations",
    tag: "Photography",
    summary:
      "Add an annotation layer to an accepted, unarchived photo. A client UUIDv7 is accepted for layers drawn offline.",
    auth: perm("photo.annotate"),
    params: PhotoParams,
    body: PhotoAnnotationCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: PhotoAnnotation, etag: true },
    notFound: "PHOTO_NOT_FOUND",
    audit: ["PHOTO_ANNOTATED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "updatePhotoAnnotation",
    method: "PATCH",
    path: "/patients/{patientId}/photos/{photoId}/annotations/{annotationId}",
    tag: "Photography",
    summary: "Change one's own annotation layer.",
    auth: perm("photo.annotate"),
    params: AnnotationParams,
    body: PhotoAnnotationUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: PhotoAnnotation, etag: true },
    notFound: "PHOTO_ANNOTATION_NOT_FOUND",
    audit: ["PHOTO_ANNOTATED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "deletePhotoAnnotation",
    method: "DELETE",
    path: "/patients/{patientId}/photos/{photoId}/annotations/{annotationId}",
    tag: "Photography",
    summary: "Delete one's own annotation layer. The row is kept, marked deleted.",
    auth: perm("photo.annotate"),
    params: AnnotationParams,
    ifMatch: "required",
    response: { status: 204, shape: "none" },
    notFound: "PHOTO_ANNOTATION_NOT_FOUND",
    audit: ["PHOTO_ANNOTATED"],
    patientData: true,
    errors: [409],
  },
  // ---- Before / after (spec §6.3 "Before / after"; ADR-0026 K3-11 to K3-13) -------
  {
    operationId: "listBeforeAfterSets",
    method: "GET",
    path: "/patients/{patientId}/before-after",
    tag: "Photography",
    summary: "The patient's before/after sets, newest first.",
    auth: perm("photo.view"),
    params: PatientParam,
    query: BeforeAfterSetListQuery,
    response: { status: 200, shape: "collection", schema: BeforeAfterSet },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createBeforeAfterSet",
    method: "POST",
    path: "/patients/{patientId}/before-after",
    tag: "Photography",
    summary:
      "Pair two photos of this patient with the same view, the before one earlier. Unknown or other " +
      "patients' photos answer the same 404.",
    auth: perm("photo.view"),
    params: PatientParam,
    body: BeforeAfterSetCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: BeforeAfterSet, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["BEFORE_AFTER_CREATED"],
    patientData: true,
    errors: [409, 422],
  },
  {
    operationId: "getBeforeAfterSet",
    method: "GET",
    path: "/patients/{patientId}/before-after/{setId}",
    tag: "Photography",
    summary: "One set, with its registration.",
    auth: perm("photo.view"),
    params: SetParams,
    response: { status: 200, shape: "resource", schema: BeforeAfterSet, etag: true },
    notFound: "BEFORE_AFTER_SET_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "requestBeforeAfterRegistration",
    method: "POST",
    path: "/patients/{patientId}/before-after/{setId}/auto-registration",
    tag: "Photography",
    summary:
      "Queue automatic alignment of the set from its display previews. The result applies only if " +
      "the set has not changed meanwhile.",
    auth: perm("photo.annotate"),
    params: SetParams,
    idempotency: "required",
    response: { status: 202, shape: "resource", schema: BeforeAfterSet, etag: true },
    notFound: "BEFORE_AFTER_SET_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "updateBeforeAfterSet",
    method: "PATCH",
    path: "/patients/{patientId}/before-after/{setId}",
    tag: "Photography",
    summary: "Rename the set, align it by hand, or reset its alignment.",
    auth: perm("photo.annotate"),
    params: SetParams,
    body: BeforeAfterSetUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: BeforeAfterSet, etag: true },
    notFound: "BEFORE_AFTER_SET_NOT_FOUND",
    patientData: true,
  },
  // ---- Exports (spec §6.3; ADR-0026 K3-14, K3-15; ADR-0027) ------------------------
  {
    operationId: "createPhotoExport",
    method: "POST",
    path: "/patients/{patientId}/photos/{photoId}/exports",
    tag: "Photography",
    summary:
      "Export an accepted photo for one purpose, optionally with one annotation layer drawn in. Needs " +
      "the patient's current grant for the purpose; renders asynchronously.",
    auth: EXPORTER,
    stepUp: true,
    params: PhotoParams,
    body: PhotoExportCreate,
    idempotency: "required",
    response: { status: 202, shape: "resource", schema: MediaExport },
    notFound: "PHOTO_NOT_FOUND",
    audit: ["PHOTO_EXPORTED"],
    patientData: true,
    errors: [409, 429],
  },
  {
    operationId: "createBeforeAfterExport",
    method: "POST",
    path: "/patients/{patientId}/before-after/{setId}/exports",
    tag: "Photography",
    summary:
      "Export the set side by side, the after photo placed by the set's alignment. Needs the current " +
      "grant for the purpose on both photos; renders asynchronously.",
    auth: EXPORTER,
    stepUp: true,
    params: SetParams,
    body: BeforeAfterExportCreate,
    idempotency: "required",
    response: { status: 202, shape: "resource", schema: MediaExport },
    notFound: "BEFORE_AFTER_SET_NOT_FOUND",
    audit: ["PHOTO_EXPORTED"],
    patientData: true,
    errors: [409, 429],
  },
  {
    operationId: "getExport",
    method: "GET",
    path: "/patients/{patientId}/exports/{exportId}",
    tag: "Photography",
    summary: "An export's status: pending, ready, failed or revoked.",
    auth: EXPORTER,
    stepUp: true,
    params: ExportParams,
    response: { status: 200, shape: "resource", schema: MediaExport },
    notFound: "EXPORT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createExportAccessUrl",
    method: "POST",
    path: "/patients/{patientId}/exports/{exportId}/access-urls",
    tag: "Photography",
    summary:
      "A signed GET for a ready export, valid 10 minutes, while its release is active and the grant " +
      "still holds. One PHOTO_VIEWED per photo shown.",
    auth: EXPORTER,
    stepUp: true,
    params: ExportParams,
    response: { status: 201, shape: "resource", schema: ExportAccessUrl },
    notFound: "EXPORT_NOT_FOUND",
    audit: ["PHOTO_VIEWED"],
    patientData: true,
    errors: [409, 503],
  },
  // ---- Consultations (spec §6.3 "Consultations", §5.4.1; ADR-0026) ---------------
  {
    operationId: "listConsultations",
    method: "GET",
    path: "/patients/{patientId}/consultations",
    tag: "Consultations",
    summary: "The patient's consultations, newest first. Archived ones only when asked for.",
    auth: perm("consultation.create"),
    params: PatientParam,
    query: ConsultationListQuery,
    response: { status: 200, shape: "collection", schema: Consultation },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createConsultation",
    method: "POST",
    path: "/patients/{patientId}/consultations",
    tag: "Consultations",
    summary: "Create a DRAFT consultation in a practice within the caller's scope.",
    auth: perm("consultation.create"),
    params: PatientParam,
    body: ConsultationCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: Consultation, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["CONSULTATION_CREATED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "getConsultation",
    method: "GET",
    path: "/patients/{patientId}/consultations/{consultationId}",
    tag: "Consultations",
    summary: "One consultation, with the completion preconditions it still fails.",
    auth: perm("consultation.create"),
    params: ConsultationParams,
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "updateConsultation",
    method: "PATCH",
    path: "/patients/{patientId}/consultations/{consultationId}",
    tag: "Consultations",
    summary: "Change the reason, primary provider or location while the content is open (ADR-0026 K3-02).",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    body: ConsultationUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "startConsultation",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/start",
    tag: "Consultations",
    summary: "DRAFT to IN_PROGRESS.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_STATUS_CHANGED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "requestConsultationInformation",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/request-information",
    tag: "Consultations",
    summary: "IN_PROGRESS to AWAITING_INFORMATION.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_STATUS_CHANGED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "resumeConsultation",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/resume",
    tag: "Consultations",
    summary: "AWAITING_INFORMATION to IN_PROGRESS.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_STATUS_CHANGED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "submitConsultationForReview",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/submit-for-review",
    tag: "Consultations",
    summary: "IN_PROGRESS or AWAITING_INFORMATION to READY_FOR_REVIEW; no note may be a draft.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_STATUS_CHANGED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "returnConsultationToProgress",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/return-to-progress",
    tag: "Consultations",
    summary: "READY_FOR_REVIEW to IN_PROGRESS, to change the reviewed content.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_STATUS_CHANGED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "cancelConsultation",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/cancel",
    tag: "Consultations",
    summary: "Cancel a consultation that is not final, with a reason (ADR-0026 K3-05).",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    body: ConsultationCancel,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_STATUS_CHANGED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "completeConsultation",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/complete",
    tag: "Consultations",
    summary: "READY_FOR_REVIEW to COMPLETED once every precondition holds; 422 names the unmet ones.",
    auth: perm("consultation.complete"),
    params: ConsultationParams,
    body: ConsultationComplete,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_COMPLETED"],
    patientData: true,
    errors: [409, 422],
  },
  {
    operationId: "archiveConsultation",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/archive",
    tag: "Consultations",
    summary: "Archive a completed or cancelled consultation. Nothing is deleted.",
    auth: perm("consultation.complete"),
    params: ConsultationParams,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["CONSULTATION_STATUS_CHANGED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "putConsultationConcerns",
    method: "PUT",
    path: "/patients/{patientId}/consultations/{consultationId}/concerns",
    tag: "Consultations",
    summary: "Replace the concerns this consultation addresses, while its content is open.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    body: ConsultationConcernsPut,
    response: { status: 200, shape: "resource", schema: Consultation, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "listConsultationNotes",
    method: "GET",
    path: "/patients/{patientId}/consultations/{consultationId}/notes",
    tag: "Consultations",
    summary: "The consultation's notes, oldest first, each addendum after the note it corrects.",
    auth: perm("consultation.create"),
    params: ConsultationParams,
    query: ConsultationNoteListQuery,
    response: { status: 200, shape: "collection", schema: ConsultationNote },
    notFound: "CONSULTATION_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createConsultationNote",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/notes",
    tag: "Consultations",
    summary: "Draft a note, or an addendum to a FINAL note. A client UUIDv7 is accepted for offline drafts.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    body: ConsultationNoteCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: ConsultationNote, etag: true },
    notFound: "CONSULTATION_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "updateConsultationNote",
    method: "PATCH",
    path: "/patients/{patientId}/consultations/{consultationId}/notes/{noteId}",
    tag: "Consultations",
    summary: "Change one's own DRAFT note.",
    auth: perm("consultation.edit"),
    params: NoteParams,
    body: ConsultationNoteUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: ConsultationNote, etag: true },
    notFound: "CONSULTATION_NOTE_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "deleteConsultationNote",
    method: "DELETE",
    path: "/patients/{patientId}/consultations/{consultationId}/notes/{noteId}",
    tag: "Consultations",
    summary: "Discard one's own DRAFT note. A FINAL note is never deleted.",
    auth: perm("consultation.edit"),
    params: NoteParams,
    ifMatch: "required",
    response: { status: 204, shape: "none" },
    notFound: "CONSULTATION_NOTE_NOT_FOUND",
    patientData: true,
    errors: [409],
  },
  {
    operationId: "finalizeConsultationNote",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/notes/{noteId}/finalize",
    tag: "Consultations",
    summary: "Finalize one's own DRAFT note. It is then immutable (UD-15).",
    auth: perm("consultation.edit"),
    params: NoteParams,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: ConsultationNote, etag: true },
    notFound: "CONSULTATION_NOTE_NOT_FOUND",
    audit: ["CONSULTATION_NOTE_FINALIZED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "generateConsultationSummary",
    method: "POST",
    path: "/patients/{patientId}/consultations/{consultationId}/summary",
    tag: "Consultations",
    summary:
      "Generate the summary PDF as a new version of the consultation's summary document: in " +
      "READY_FOR_REVIEW, or when completed and an addendum was finalized since the last summary.",
    auth: perm("consultation.edit"),
    params: ConsultationParams,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: Document },
    notFound: "CONSULTATION_NOT_FOUND",
    audit: ["DOCUMENT_ADDED"],
    patientData: true,
    errors: [409],
  },
  {
    operationId: "listPatientConcerns",
    method: "GET",
    path: "/patients/{patientId}/concerns",
    tag: "Patients",
    summary: "The patient's aesthetic concerns. Clinical: not readable with patient.read alone.",
    auth: perm("consultation.create"),
    params: PatientParam,
    query: PatientConcernListQuery,
    response: { status: 200, shape: "collection", schema: PatientConcern },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createPatientConcern",
    method: "POST",
    path: "/patients/{patientId}/concerns",
    tag: "Patients",
    summary: "Record a concern by area (ADR-0026 K3-08).",
    auth: perm("consultation.edit"),
    params: PatientParam,
    body: PatientConcernCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: PatientConcern, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
  },
  {
    operationId: "updatePatientConcern",
    method: "PATCH",
    path: "/patients/{patientId}/concerns/{concernId}",
    tag: "Patients",
    summary: "Change a concern's description, or mark it resolved.",
    auth: perm("consultation.edit"),
    params: ConcernParams,
    body: PatientConcernUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: PatientConcern, etag: true },
    notFound: "PATIENT_CONCERN_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
  },
  {
    operationId: "listMedicalHistory",
    method: "GET",
    path: "/patients/{patientId}/medical-history",
    tag: "Patients",
    summary: "Allergies, medications, conditions and prior procedures. Not readable with patient.read alone.",
    auth: perm("consultation.create"),
    params: PatientParam,
    query: MedicalHistoryListQuery,
    response: { status: 200, shape: "collection", schema: MedicalHistoryEntry },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createMedicalHistoryEntry",
    method: "POST",
    path: "/patients/{patientId}/medical-history",
    tag: "Patients",
    summary: "Record a history entry (source STAFF).",
    auth: perm("consultation.edit"),
    params: PatientParam,
    body: MedicalHistoryCreate,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: MedicalHistoryEntry, etag: true },
    notFound: "PATIENT_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
  },
  {
    operationId: "updateMedicalHistoryEntry",
    method: "PATCH",
    path: "/patients/{patientId}/medical-history/{entryId}",
    tag: "Patients",
    summary: "Correct a history entry. Entries are never deleted.",
    auth: perm("consultation.edit"),
    params: HistoryParams,
    body: MedicalHistoryUpdate,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: MedicalHistoryEntry, etag: true },
    notFound: "MEDICAL_HISTORY_ENTRY_NOT_FOUND",
    audit: ["PATIENT_UPDATED"],
    patientData: true,
  },
  {
    operationId: "getPatientTimeline",
    method: "GET",
    path: "/patients/{patientId}/timeline",
    tag: "Patients",
    summary:
      "The patient's history, newest first, from the domain tables. Each item appears only to a caller " +
      "who can read its domain. Metadata only.",
    auth: perm("patient.read"),
    params: PatientParam,
    query: TimelineQuery,
    response: { status: 200, shape: "collection", schema: TimelineItem },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  // ---- Documents (spec §6.3 "Documents"; ADR-0026 K3-16; ADR-0027) ---------------
  {
    operationId: "listDocuments",
    method: "GET",
    path: "/patients/{patientId}/documents",
    tag: "Documents",
    summary: "The patient's documents, newest first, with their versions.",
    auth: perm("document.read"),
    params: PatientParam,
    query: DocumentListQuery,
    response: { status: 200, shape: "collection", schema: Document },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "getDocument",
    method: "GET",
    path: "/patients/{patientId}/documents/{documentId}",
    tag: "Documents",
    summary: "One document with its versions.",
    auth: perm("document.read"),
    params: DocumentParams,
    response: { status: 200, shape: "resource", schema: Document },
    notFound: "DOCUMENT_NOT_FOUND",
    patientData: true,
  },
  {
    operationId: "createDocumentUpload",
    method: "POST",
    path: "/patients/{patientId}/documents/uploads",
    tag: "Documents",
    summary:
      "Start uploading a PDF (at most 50 MiB) as a new document or a new version of an uploaded one. " +
      "Returns a write-once PUT carrying the checksum.",
    auth: perm("document.manage"),
    params: PatientParam,
    body: DocumentUploadRequest,
    idempotency: "required",
    response: { status: 201, shape: "resource", schema: DocumentUploadIntent },
    notFound: "PATIENT_NOT_FOUND",
    patientData: true,
    errors: [409, 503],
  },
  {
    operationId: "completeDocumentUpload",
    method: "POST",
    path: "/patients/{patientId}/documents/{documentId}/complete-upload",
    tag: "Documents",
    summary:
      "Verify the uploaded file (size, SHA-256, a PDF) and add it as the next version, which is " +
      "served once its malware scan is clean.",
    auth: perm("document.manage"),
    params: DocumentParams,
    body: DocumentUploadComplete,
    idempotency: "required",
    response: { status: 200, shape: "resource", schema: Document },
    notFound: "DOCUMENT_NOT_FOUND",
    audit: ["DOCUMENT_ADDED"],
    patientData: true,
    errors: [409, 413, 415, 422, 503],
  },
  {
    operationId: "createDocumentAccessUrl",
    method: "POST",
    path: "/patients/{patientId}/documents/{documentId}/access-urls",
    tag: "Documents",
    summary: "A signed download of an available version, valid 10 minutes, as an attachment.",
    auth: perm("document.read"),
    params: DocumentParams,
    body: DocumentAccessUrlRequest,
    response: { status: 201, shape: "resource", schema: DocumentAccessUrl },
    notFound: "DOCUMENT_NOT_FOUND",
    audit: ["DOCUMENT_VIEWED"],
    patientData: true,
    errors: [409, 503],
  },
  // ---- Audit, settings, health -------------------------------------------------
  {
    operationId: "listAuditEvents",
    method: "GET",
    path: "/audit/events",
    tag: "Audit",
    summary: "Audit events of the organization (platform scope: platform-level events only), newest first.",
    auth: perm("audit.read", "organization", "platform"),
    query: AuditEventQuery,
    response: { status: 200, shape: "collection", schema: AuditEvent },
  },
  {
    operationId: "getAuditEvent",
    method: "GET",
    path: "/audit/events/{id}",
    tag: "Audit",
    summary: "One audit event.",
    auth: perm("audit.read", "organization", "platform"),
    params: IdParam,
    response: { status: 200, shape: "resource", schema: AuditEvent },
    notFound: "AUDIT_EVENT_NOT_FOUND",
  },
  {
    operationId: "getOrganizationSetting",
    method: "GET",
    path: "/settings/organization/{key}",
    tag: "Settings",
    summary: "An organization policy setting, or its default.",
    auth: perm("configuration.manage"),
    params: SettingParam,
    response: { status: 200, shape: "resource", schema: OrganizationSetting, etag: true },
    notFound: "SETTING_NOT_FOUND",
  },
  {
    operationId: "putOrganizationSetting",
    method: "PUT",
    path: "/settings/organization/{key}",
    tag: "Settings",
    summary: 'Set a policy setting. If-Match is required; a setting still at its default has ETag "v0".',
    auth: perm("configuration.manage"),
    params: SettingParam,
    body: OrganizationSettingPut,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: OrganizationSetting, etag: true },
    notFound: "SETTING_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
  },
  {
    operationId: "listFeatureFlags",
    method: "GET",
    path: "/feature-flags",
    tag: "Settings",
    summary: "Every registered flag's value for the organization, or for one practice.",
    auth: SESSION,
    query: FeatureFlagQuery,
    response: { status: 200, shape: "collection", schema: FeatureFlag },
  },
  {
    operationId: "getFeatureFlag",
    method: "GET",
    path: "/feature-flags/{key}",
    tag: "Settings",
    summary: "One flag's value and where it comes from.",
    auth: perm("configuration.manage"),
    params: SettingParam,
    query: FeatureFlagQuery,
    response: { status: 200, shape: "resource", schema: FeatureFlag },
    notFound: "FEATURE_FLAG_NOT_FOUND",
  },
  {
    operationId: "putFeatureFlag",
    method: "PUT",
    path: "/feature-flags/{key}",
    tag: "Settings",
    summary: "Turn a flag on or off for the organization or one practice. A flag never grants access.",
    auth: perm("configuration.manage"),
    params: SettingParam,
    body: FeatureFlagPut,
    response: { status: 200, shape: "resource", schema: FeatureFlag },
    notFound: "FEATURE_FLAG_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
  },
  {
    operationId: "getOfflineCachePolicy",
    method: "GET",
    path: "/settings/offline-cache-policy",
    tag: "Settings",
    summary: "The offline cache policy the provider app applies: the strictest of the caller's practices.",
    auth: SESSION,
    response: { status: 200, shape: "resource", schema: EffectiveOfflineCachePolicy },
  },
  {
    operationId: "getPracticeSetting",
    method: "GET",
    path: "/settings/practices/{practiceId}/{key}",
    tag: "Settings",
    summary: "A practice setting, or its default.",
    auth: perm("configuration.manage"),
    params: PracticeSettingParams,
    response: { status: 200, shape: "resource", schema: PracticeSetting, etag: true },
    notFound: "SETTING_NOT_FOUND",
  },
  {
    operationId: "putPracticeSetting",
    method: "PUT",
    path: "/settings/practices/{practiceId}/{key}",
    tag: "Settings",
    summary: 'Set a practice setting. If-Match is required; a setting still at its default has ETag "v0".',
    auth: perm("configuration.manage"),
    params: PracticeSettingParams,
    body: PracticeSettingPut,
    ifMatch: "required",
    response: { status: 200, shape: "resource", schema: PracticeSetting, etag: true },
    notFound: "SETTING_NOT_FOUND",
    audit: ["CONFIGURATION_CHANGED"],
  },
  {
    operationId: "listRetentionPolicies",
    method: "GET",
    path: "/retention-policies",
    tag: "Settings",
    summary: "The organization's retention policies, newest first. Recorded only; nothing runs them yet.",
    auth: perm("configuration.manage"),
    query: RetentionPolicyListQuery,
    response: { status: 200, shape: "collection", schema: RetentionPolicy },
  },
  {
    operationId: "createRetentionPolicy",
    method: "POST",
    path: "/retention-policies",
    tag: "Settings",
    summary: "Record a retention policy. DELETE is refused until legal hold exists (UD-24).",
    auth: perm("configuration.manage"),
    body: RetentionPolicyCreate,
    response: { status: 201, shape: "resource", schema: RetentionPolicy },
    audit: ["CONFIGURATION_CHANGED"],
    errors: [409],
  },
  {
    operationId: "getLiveness",
    method: "GET",
    path: "/health/live",
    tag: "Health",
    summary: "The process is up. No data and no dependency details.",
    auth: PUBLIC,
    response: { status: 200, shape: "bare", schema: HealthStatus },
  },
  {
    operationId: "getReadiness",
    method: "GET",
    path: "/health/ready",
    tag: "Health",
    summary: "The process can serve requests (database reachable). 503 otherwise.",
    auth: PUBLIC,
    response: { status: 200, shape: "bare", schema: HealthStatus },
    errors: [503],
  },
] as const satisfies readonly EndpointDefinition[];

export type OperationId = (typeof ENDPOINTS)[number]["operationId"];

export function endpoint(operationId: OperationId): EndpointDefinition {
  const found = ENDPOINTS.find((e) => e.operationId === operationId);
  if (found === undefined) throw new Error(`Unknown operation ${operationId}`);
  return found;
}

/** `/patients/{patientId}` → `/patients/:patientId` (Fastify/NestJS form). */
export function routePath(path: string): string {
  return path.replace(/\{(\w+)\}/g, ":$1");
}

/** Every error status an endpoint can return, from its auth, inputs and headers. */
export function errorStatuses(e: EndpointDefinition): number[] {
  // 503: any operation can meet a saturated database (retry after Retry-After).
  const statuses = new Set<number>([400, 500, 503, ...(e.errors ?? [])]);
  if (e.auth.kind !== "public") statuses.add(401);
  if (e.auth.kind === "permission" || e.stepUp) statuses.add(403);
  if (e.params !== undefined || e.notFound !== undefined) statuses.add(404);
  if (e.idempotency !== undefined) statuses.add(409);
  if (e.ifMatch !== undefined) {
    statuses.add(412);
    if (e.ifMatch === "required") statuses.add(428);
  }
  return [...statuses].sort((a, b) => a - b);
}

/** Settings keys accepted in the path, for documentation. */
export const SettingKeyParam = OrganizationSettingKeySchema;
