-- Second factors count only once confirmed (ADR-0021). Generated by
-- prisma migrate diff from the design schema; passwords are confirmed on creation.

-- AlterTable
ALTER TABLE "UserCredential" ADD COLUMN     "confirmedAt" TIMESTAMPTZ(3);

UPDATE "UserCredential" SET "confirmedAt" = "createdAt" WHERE "type" = 'PASSWORD';

-- Platform security checks for a confirmed factor before an MFA reset (step-up).
GRANT SELECT ("confirmedAt") ON "UserCredential" TO aestara_platform;

-- A platform bootstrap that re-invites an organization's first administrator
-- supersedes the earlier invitation (ADR-0021).
GRANT UPDATE ("consumedAt") ON "UserToken" TO aestara_platform;
