#!/usr/bin/env python3
"""Writes docs/SOFTWARE_PRODUCTION_BIBLE.md, the verbatim text export of the
Production Bible PDF required by Bible §35.

The words are not edited: section headings become Markdown headings for
navigation, and each section's text is kept in a fenced block so the PDF's
wording and line layout survive unchanged. The PDF stays authoritative.

Usage:   pip install pypdf && python3 docs/technical-spec/verification/export_bible.py [--check]
--check exits 1 when the committed export differs from a fresh one.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[3]
PDF = ROOT / "Aesthetic_Platform_Software_Production_Bible_v1.0.pdf"
OUT = ROOT / "docs" / "SOFTWARE_PRODUCTION_BIBLE.md"
RUNNING_HEADERS = ("Aesthetic Platform - Software Production Bible", "Confidential Product Specification | Page")


def pdf_lines() -> list[str]:
    lines: list[str] = []
    for page in PdfReader(str(PDF)).pages:
        for line in (page.extract_text() or "").splitlines():
            if line.startswith(RUNNING_HEADERS):
                continue
            lines.append(line.replace("", "•").rstrip())
    return lines


def is_top_heading(line: str, expected: int) -> bool:
    match = re.match(r"^(\d{1,2})\. (\S.*)$", line)
    if not match or int(match.group(1)) != expected:
        return False
    title = match.group(2)
    return title[0].isupper() and not title.endswith((".", "?", ","))


def render() -> str:
    lines = pdf_lines()
    digest = hashlib.sha256(PDF.read_bytes()).hexdigest()
    out = [
        "# Software Production Bible v1.0 (text export)",
        "",
        "| | |",
        "|---|---|",
        f"| Source | `{PDF.name}` (repository root), SHA-256 `{digest}` |",
        "| Status | Verbatim text export required by Bible §35. **The PDF is authoritative**; if this file and the PDF ever differ, the PDF wins. |",
        "| Classification | Marked *Confidential Product Specification* in the source. |",
        "| Generated by | `docs/technical-spec/verification/export_bible.py`, checked for drift in CI. Do not edit by hand. |",
        "",
        "Headings are added for navigation only; the text of each section is reproduced unchanged inside the block that follows its heading.",
        "",
    ]
    body: list[str] = []
    expected_top = 0
    current_top: int | None = None

    def flush() -> None:
        while body and not body[-1].strip():
            body.pop()
        while body and not body[0].strip():
            body.pop(0)
        if body:
            out.extend(["```text", *body, "```", ""])
        body.clear()

    for line in lines:
        stripped = line.strip()
        if is_top_heading(stripped, expected_top):
            flush()
            out.extend([f"## {stripped}", ""])
            current_top = expected_top
            expected_top += 1
            continue
        sub = re.match(r"^(\d{1,2})\.(\d{1,2}) (\S.*)$", stripped)
        if sub and current_top is not None and int(sub.group(1)) == current_top and sub.group(3)[0].isupper():
            flush()
            out.extend([f"### {stripped}", ""])
            continue
        if re.match(r"^Appendix [A-Z] - ", stripped):
            flush()
            out.extend([f"## {stripped}", ""])
            current_top = None
            continue
        body.append(line.replace("```", "'''"))
    flush()
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print("SOFTWARE_PRODUCTION_BIBLE.md is out of date: run export_bible.py")
            return 1
        print("SOFTWARE_PRODUCTION_BIBLE.md matches the PDF")
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
